### ISSUE TITLE
 ok/ok.h: No such file or directory

### ISSUE THREAD

**Issue by andreykyz** [littlstar/b64.c#11]
Makefile build failed:

> make
> cc -std=c99 -Wall -Ideps   -c -o test.o test.c
> test.c:12:19: fatal error: ok/ok.h: No such file or directory
> compilation terminated.
> <builtin>: recipe for target 'test.o' failed
> make: *** [test.o] Error 1

**Comment by jwerle** [comment]
@andreykyz did you install the deps with `clib install` first?

**Comment by fantuz** [comment]
i did install deps with suggested command (as in README.md) but '<ok/ok.h>' still pose problem...
any hint ?

**Comment by fantuz** [comment]
allright, I managed install the "libok" by
```
clib install jwerle/libok
       fetch : jwerle/libok:package.json

```
